# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=100)),
                ('user_passwd', models.CharField(max_length=16)),
                ('user_name', models.CharField(max_length=50)),
                ('user_birth', models.DateField()),
                ('user_gender', models.BooleanField(default=False)),
                ('user_profile_image', models.ImageField(height_field=100, upload_to=b'', width_field=100)),
                ('user_curver', models.ImageField(upload_to=b'')),
                ('user_phone_number', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('user_name',),
            },
        ),
    ]
